name: Deploy to AWS using Python CDK

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Install Requirements
        run: 'pip3 install -r requirements.txt'

      - name: CDK Synth
        run: cdk synth

      - name: CDK Deploy
        run: cdk deploy --require-approval never
